# Generated by Django 4.0.3 on 2022-04-10 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
